version: 2
jobs:
  Build:
    docker:
      - image: circleci/node:12.14-browsers
    steps:
      - checkout
      - restore_cache:
          key: splus-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn
      - save_cache:
          name: Save SPlus packages
          key: splus-packages-{{ checksum "yarn.lock" }}
          paths: node_modules
      - persist_to_workspace:
          root: .
          paths: node_modules
  Unit-Tests:
    docker:
      - image: circleci/node:12.14-browsers
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Yarn test
          command: yarn test
  Publish:
    docker:
      - image: circleci/node:12.14-browsers
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Publish
          command: yarn build
      - run: ls -a
workflows:
  version: 2
  Build-and-deploy:
    jobs:
      - Build
      - Unit-Tests:
          requires:
            - Build
      - Publish:
          requires:
            - Unit-Tests
