version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.15
jobs:
  Deploy-Static-Site:
    docker:
      - image: circleci/node:12.14-browsers
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Build storybook static page
          command: yarn build-public
      - aws-s3/sync:
          from: public
          to: s3://splus.alexhomingwong.co.uk
  Build:
    docker:
      - image: circleci/node:12.14-browsers
    steps:
      - checkout
      - restore_cache:
          key: splus-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn
      - save_cache:
          name: Save SPlus packages
          key: splus-packages-{{ checksum "yarn.lock" }}
          paths: node_modules
      - persist_to_workspace:
          root: .
          paths: node_modules
  Unit-Tests:
    docker:
      - image: circleci/node:12.14-browsers
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Yarn test
          command: yarn test
  Publish:
    docker:
      - image: circleci/node:12.14-browsers
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Build package
          command: yarn build
      - run:
          name: Authenticate with NPM
          command: echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
      - run:
          name: Publish to NPM
          command: npm publish
workflows:
  version: 2
  Build-and-Publish:
    jobs:
      - Build:
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
      - Unit-Tests:
          requires:
            - Build
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
      - Publish:
          requires:
            - Unit-Tests
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+$/
      - Deploy-Static-Site:
          requires:
            - Publish
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+$/
