version: 2
jobs:
  Deploy-Static-Site:
    docker:
      - image: circleci/node:12.14-browsers
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Install AWS CLI
          command: |
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
      - run:
          name: Build storybook static page
          command: yarn build-public
      - run:
          name: Sync S3 Bucket
          command: aws s3 sync public s3://splus.alexhomingwong.co.uk
  Build:
    docker:
      - image: circleci/node:12.14-browsers
    steps:
      - checkout
      - restore_cache:
          key: splus-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn
      - save_cache:
          name: Save SPlus packages
          key: splus-packages-{{ checksum "yarn.lock" }}
          paths: node_modules
      - persist_to_workspace:
          root: .
          paths: node_modules
  Unit-Tests:
    docker:
      - image: circleci/node:12.14-browsers
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Yarn test
          command: yarn test
  Publish:
    docker:
      - image: circleci/node:12.14-browsers
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Build package
          command: yarn build
      - run:
          name: Authenticate with NPM
          command: echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
      - run:
          name: Publish to NPM
          command: npm publish
workflows:
  version: 2
  Build-and-Publish:
    jobs:
      - Build
      - Unit-Tests:
          requires:
            - Build
      - Publish:
          requires:
            - Unit-Tests
          filters:
            branches:
              only:
                - master
      - Deploy-Static-Site:
          requires:
            - Publish
          filters:
            branches:
              only:
                - master
