version: 2
jobs:
  Build:
    docker:
      - image: circleci/node:12.14-browsers
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn
  Unit-Tests:
    docker:
      - image: circleci/node:12.14-browsers
    steps:
      - checkout
      - run: echo "hello world 2"
workflows:
  version: 2
  Build-and-deploy:
    jobs:
      - Build
      - Unit-Tests:
          requires:
            - Build
